

services:
  db:
    image: postgres
    container_name: mydb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TamarDehan2149!
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./Server
    container_name: backend
    ports:
      - "7106:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydb;Username=postgres;Password=TamarDehan2149!

  frontend:
    build:
      context: ./Client
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

