--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Invoices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Invoices" (
    "InvoiceId" integer NOT NULL,
    "InvoiceNumber" character varying(50) NOT NULL,
    "IssueDate" timestamp with time zone NOT NULL,
    "DueDate" timestamp with time zone,
    "TotalAmount" numeric(18,2) NOT NULL,
    "PaidAmount" numeric(18,2) NOT NULL,
    "Status" integer NOT NULL,
    "ClientName" character varying(50),
    "ClientEmail" character varying(50),
    "Description" character varying(200),
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Invoices" OWNER TO postgres;

--
-- Name: Invoices_InvoiceId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Invoices" ALTER COLUMN "InvoiceId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Invoices_InvoiceId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Payments" (
    "PaymentId" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Currency" integer NOT NULL,
    "PaymentDate" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "Method" integer NOT NULL,
    "ReferenceNumber" character varying(100),
    "Notes" character varying(500),
    "InvoiceId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Payments" OWNER TO postgres;

--
-- Name: Payments_PaymentId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Payments" ALTER COLUMN "PaymentId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Payments_PaymentId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Invoices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Invoices" ("InvoiceId", "InvoiceNumber", "IssueDate", "DueDate", "TotalAmount", "PaidAmount", "Status", "ClientName", "ClientEmail", "Description", "CreatedAt") FROM stdin;
\.


--
-- Data for Name: Payments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Payments" ("PaymentId", "Amount", "Currency", "PaymentDate", "Status", "Method", "ReferenceNumber", "Notes", "InvoiceId", "CreatedAt") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250722190347_InitialCreate	9.0.7
\.


--
-- Name: Invoices_InvoiceId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Invoices_InvoiceId_seq"', 1, false);


--
-- Name: Payments_PaymentId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Payments_PaymentId_seq"', 1, false);


--
-- Name: Invoices PK_Invoices; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Invoices"
    ADD CONSTRAINT "PK_Invoices" PRIMARY KEY ("InvoiceId");


--
-- Name: Payments PK_Payments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Payments"
    ADD CONSTRAINT "PK_Payments" PRIMARY KEY ("PaymentId");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Payments_InvoiceId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Payments_InvoiceId" ON public."Payments" USING btree ("InvoiceId");


--
-- Name: Payments FK_Payments_Invoices_InvoiceId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Payments"
    ADD CONSTRAINT "FK_Payments_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES public."Invoices"("InvoiceId") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

